### ISSUE TITLE
Editor causing crashes in Ableton Live on document close / app exit

### ISSUE THREAD

**Issue by jdnorthrup** [AURAPluginsLtd/Access-Virus-Editor#42] opened 2023-01-17 00:28 UTC
Hi,
I have the latest version of the AURA Virus Editor in my Ableton Live template project. Whenever I quit Live, for the most part I get a delay in app shutdown followed by a crash report. This also happens sometimes when I close the document.

Here's the top of the report from the crash. I'm using Mac OS 10.14.6, Ableton Live 11.2.7, and the latest Virus editor version.

```
Process:               Live [1099]
Path:                  /Applications/Ableton Live 11 Suite.app/Contents/MacOS/Live
Identifier:            com.ableton.live
Version:               11.2.7 [2022-12-08_2509d781e7] (11.2.7 [2022-12-08_2509d781e7])
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Live [1099]
User ID:               501

Date/Time:             2023-01-16 16:28:07.126 -0800
OS Version:            Mac OS X 10.14.6 (18G9323)
Report Version:        12
Anonymous UUID:        564B00AA-34A6-7BE0-4DA8-0CA0A4900059


Time Awake Since Boot: 800 seconds

System Integrity Protection: enabled

Crashed Thread:        0  MainThread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Performing @selector(quit:) from sender NSMenuItem 0x600002c01c80
abort() called
Live(1099,0x1145a75c0) malloc: *** error for object 0x70000606c000: pointer being freed was not allocated
 

Thread 0 Crashed:: MainThread  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff7ce0f2c2 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff7cecabf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff7cd796a6 abort + 127
3   libsystem_malloc.dylib        	0x00007fff7ce88077 malloc_vreport + 545
4   libsystem_malloc.dylib        	0x00007fff7ce87e38 malloc_report + 151
5   com.AURAPlugins.audiounit.AccessVirusEditor	0x000000014dc588a4 VirusEditor::~VirusEditor() + 388
6   com.AURAPlugins.audiounit.AccessVirusEditor	0x000000014dc62880 iplug::IPlugAUFactory<VirusEditor, true>::Close(void*) + 16
7   com.apple.audio.toolbox.AudioToolbox	0x00007fff4f437a1e APComponentInstance::disposeInstance() + 30
8   com.apple.audio.toolbox.AudioToolbox	0x00007fff4f4379d3 AudioComponentInstanceDispose + 378
9   com.ableton.live              	0x000000010881bb68 0x106442000 + 37591912
10  com.ableton.live              	0x0000000108823e42 0x106442000 + 37625410
11  com.ableton.live              	0x000000010882402e 0x106442000 + 37625902
12  com.ableton.live              	0x00000001076d8606 0x106442000 + 19490310
13  com.ableton.live              	0x00000001076dee08 0x106442000 + 19516936
```

**Comment by Guod3** [comment] 2023-01-17 03:30
I use VHE hosted in a Vienna Ensemble Pro 7 server in my Ableton 11 template. Closing the Ableton session (or loading another session from the file menu) would frequently crash the VEP7 server. I use 3 instances of VHE on various synths. I suspect that having the GUI open on every instance helps to avoid the VEP7 crash when quitting Ableton. I've avoided reporting this so far due to the many variables and possibly unusual operating environment I use (but personally recommend), making it difficult to debug.

**Comment by JaniKervinen** [comment] 2023-02-26 16:59
Hey @Guod3 let's hope the new build addresses this issue. There was a bug we have fixed that caused some issues during app / editor / daw exit. It should go online later tonight.

**Comment by JaniKervinen** [comment] 2023-02-26 17:00
and same goes for you @jdnorthrup as well :)

**Comment by Guod3** [comment] 2023-02-26 23:53
Look forward to trying a new build.
I can confirm with some confidence that the VEP server does not crash when each and all of the VirusHC GUI windows are open at the time of exit.  I have an AutoHotkey script that makes all the guI windows in the open state , so I don't notice the problem atm.

**Comment by jdnorthrup** [comment] 2023-02-27 00:45
Hi, I am looking forward to the new build. The webpage still lists the old
build from Nov 11 2022. I look forward to updating this thread if my crash
on exit gets resolved!

Thanks,
-JD

**Comment by JaniKervinen** [comment] 2023-02-28 16:43
alright, new build is online even though site shows different build number. try it out and see if it still crashes.

**Closed** 2023-03-13 17:31 UTC
